<a href="https://colab.research.google.com/github/hayannn/AIFFEL_STUDY/blob/main/%E1%84%89%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%8F%E1%85%B5%E1%86%BA%E1%84%85%E1%85%A5%E1%86%AB_%EA%B8%B0%EB%B0%98_%E1%84%91%E1%85%B3%E1%84%85%E1%85%A6%E1%84%8B%E1%85%B5%E1%86%B7%E1%84%8B%E1%85%AF%E1%84%8F%E1%85%B3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Estimator 이해 및 fit(), predict() 메서드
#### Estimator
- 지도학습의 모든 알고리즘을 구현한 클래스를 통칭
- Estimator 클래스는 분류 알고리즘을 구현한 클래스인 Classifier와 회귀 알고리즘을 구현한 클래스인 Regressor를 합쳐서 부른다.
- fit() : 학습, predict() : 예측

<br>

#### ├── Classifier(분류)
- 분류 구현 클래스
  - DecisionTreeClassifier
  - RandomForestClassifier
  - GradientBoostingClassifer
  - GaussianNB
  - SVC

<br>

#### ├── Regressor(회귀)
- 회귀 구현 클래스
  - LinearRegression
  - Ridge
  - Lasso
  - RandomForestRegressor
  - GradientBoostingRegressor

<br>

#### 비지도 학습 vs 지도 학습
- fit()
  - 비지도 학습 : 입력 데이터 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
  - 지도 학습 : 데이터 학습을 의미

- transform()
  - 비지도 학습에서 사용
  - 입력 데이터의 차원 변환, 클러스터링, 피쳐 추출 등의 실제 작업 수행

- fit_transform()
  - fit()과 transform() 한번에 수행

### 사이킷런의 주요 모듈
#### 예제 데이터
- `sklearn.datasets`
  - 사이킷런에 내장되어 예제로 제공하는 데이터 세트

#### 피쳐 처리
- `sklearn.preprocessing`
  - 데이터 전처리에 필요한 다양한 가공 기능 제공
  - 문자열 -> 숫자형 코드 값 인코딩, 정규화, 스케일링 등
- `sklearn.feature_selection`
  - 알고리즘에 큰 영향을 미치는 피쳐 우선순위대로 셀렉션 작업 수행하는 다양한 기능 제공
- `sklearn.feature_extraction`
  - 텍스트 데이터 또는 이미지 데이터의 벡터화된 피쳐 추출에 사용
  - 텍스트 데이터에서 Count Vectorizer 또는 Tf-Idf Vectorizer 등 생성하는 기능 제공
  - 텍스트 데이터 피쳐 추출은 sklearn.feature_extraction.text 모듈
  - 이미지 데이터 피쳐 추출은 sklearn.feature_extraction.image 모듈에 지원 API 있음.

#### 피쳐 처리 & 차원 축소
- `sklearn.decomposition`
  - 차원 축소 관련한 알고리즘을 지원하는 모듈
  - PCA, NMF, Truncated SVD 등을 통해 차원 축소 기능 수행 가능

#### 데이터 분리, 검증 & 파라미터 튜닝
- `sklearn.model_selection`
  - 교차 검증을 위한 학습용/테스트용 분리, 그리드 서치(Grid Search)로 최적 파라미터 추출 등 API 제공

#### 평가
- `sklearn.metrics`
  - 분류, 회귀, 클러스터링, 페어와이즈(Pairwise)에 대한 다양한 성능 측정 방법 제공
  - Accuracy, Precision, Recall, ROC-AUC, RMSE 등 제공

#### ML 알고리즘
- `sklearn.ensemble`
  - 앙상블 알고리즘 제공
  - 랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 등 제공
- `sklearn.linear_model`
  - 선형 회귀, 릿지(Ridge), 라쏘(Lasso) 및 로지스틱 회귀 등 회귀 관련 알고리즘 지원
  - SGD(Stochastic Gradient Descent) 관련 알고리즘 제공
- `sklearn.naive_bayes`
  - 나이브 베이즈 알고리즘 제공
  - 가우시안 NB, 다항 분포 NB 등
- `sklearn.neighbors`
  - 최근접 이웃 알고리즘 제공
  - K-NN 등
- `sklearn.svm`
  - 서포트 벡터 머신 알고리즘 제공
- `sklearn.tree`
  - 의사 결정 트리 알고리즘 제공
- `sklearn.cluster`
  - 비지도 클러스터링 알고리즘 제공
  - K-평균, 계층형, DBSCAN 등

#### 유틸리티
- `sklearn.pipline`
  - 피쳐 처리 등의 변환과 ML 알고리즘 학습,예측 등을 함께 묶어 실행할 수 있는 유틸리티 제공


### 내장된 예제 데이터 세트
- 분류 또는 회귀 연습용 예제 데이터(API로 제공)
  - 회귀
    - `datasets.load_boston()` : 회귀용, 미국 보스턴의 집 피쳐들과 가격에 대한 데이터 세트
    - `datasets.load_diabetes()` : 회귀용, 당뇨 데이터 세트

  - 분류
    - `datasets.load_breast_cancer()` : 분류용, 위스콘신 유방암 피쳐들과 악성/음성 레이블 데이터 세트
    - `datasets.load_digits()` : 분류용, 0~9까지 숫자의 이미지 픽셀 데이터 세트
    - `datasets.load_iris()` : 분류용, 붓꽃에 대한 피처를 가진 데이터 세트

<br>

- fetch 계열 명령
  - `fetch_covtype()` : 회귀 분석용 토지 조사 자료
  - `fetch_20newsgroups()` : 뉴스 그룹 텍스트 자료
  - `fetch_olivetti_faces()` : 얼굴 이미지 자료
  - `fetch_lfw_people()` : 얼굴 이미지 자료
  - `fetch_lfw_pairs()` : 얼굴 이미지 자료
  - `fetch_rcv1()` : 로이터 뉴스 말뭉치
  - `fetch_mldata()` : ML 웹사이트에서 다운로드

<br>

- 사이킷런에 내장된 데이터 세트는 딕셔너리 형태 -> 키 값 구성
  - 넘파이 배열(ndarray)
    - data : 피쳐의 데이터 세트
    - target : 분류 시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트
  - 넘파이 배열 또는 파이썬 리스트(list) 타입
    - target_names : 개별 레이블 이름
    - feature_names : 피처 이름
  - 스트링 타입
    - DESUR : 데이터 세트에 대한 설명과 각 피처의 설명

In [1]:
# 붓꽃 데이터 세트 생성
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))


<class 'sklearn.utils._bunch.Bunch'>


In [2]:
# load_iris() 데이터 세트 key 값 확인
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print('\n feature_names 의 type:',type(iris_data.feature_names))
print(' feature_names 의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type:',type(iris_data.target_names))
print(' feature_names 의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:',type(iris_data.data))
print(' data 의 shape:',iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:',type(iris_data.target))
print(' target 의 shape:',iris_data.target.shape)
print(iris_data.target)


 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0